---

- name: inventory2librenms playbook
  hosts: localhost
  connection: local
  tasks:
    - name: 'list of all librenms devices'
      uri:
        url: '{{ inventory2librenms_url }}/api/v0/devices?order=hostname%20DESC'
        headers:
          X-Auth-Token: '{{ inventory2librenms_token }}'
      register: register_inventory2librenms_devices_list
    - name: 'filter all hostname'
      set_fact:
        inventory2librenms_devices_list: "{{ register_inventory2librenms_devices_list | json_query('json.devices[*].hostname') }}"
    - name: 'add new devices'
      uri:
        url: '{{ inventory2librenms_url }}/api/v0/devices'
        method: POST
        headers:
          X-Auth-Token: '{{ inventory2librenms_token }}'
        body: '{{ inventory2librenms_body }}'
        body_format: json
      register: register_inventory2librenms_mew_devices
      when: item not in inventory2librenms_devices_list
      changed_when: "'has been added successfully' in register_inventory2librenms_mew_devices.json.status"
      # failed_when: "'error' in register_inventory2librenms_mew_devices.json.status"
      with_inventory_hostnames:
        - all
    - name: 'fix hostname is lower'
      uri:
        url: "{{ inventory2librenms_url }}/api/v0/devices/{{ item | lower }}/rename/{{ item }}"
        method: PATCH
        headers:
          X-Auth-Token: '{{ inventory2librenms_token }}'
      register: register_inventory2librenms_rename_devices
      changed_when: "'Device has been renamed' in register_inventory2librenms_rename_devices.json.status"
      when: item not in inventory2librenms_devices_list and not ( inventory2librenms_hostname_not_lower | default(false) )
      with_inventory_hostnames:
        - all
